junit:
  stage: test
  script:
    - mvn -B clean test
generate_artifacts:
  stage: deploy
  script:
    - mvn -B clean package -DskipTests
  artifacts:
    paths:
      - target/revolt*.jar
checkstyle:
  stage: build
  script:
    - mvn -B clean validate
generate_doc:
  stage: deploy
  script:
    - mvn -B clean javadoc:javadoc
  artifacts:
    paths:
      - target/site/apidocs/
