junit:
  stage: test
  script:
    - mvn -B clean test -Dtest=\*Test -Dcheckstyle.skip=true
generate_artifacts:
  stage: deploy
  script:
    - mvn -B clean package -DskipTests -Dmaven.javadoc.skip=true -Dcheckstyle.skip=true
  artifacts:
    paths:
      - target/revolt*.jar
checkstyle:
  stage: build
  script:
    - mvn -B clean validate
generate_doc:
  stage: deploy
  script:
    - mvn -B clean javadoc:javadoc -Dcheckstyle.skip=true
  artifacts:
    paths:
      - target/site/apidocs/
